### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by charles-dyfis-net** [systemd/casync#105]
Extracting a catar is consistently at least 3x slower than extracting a tar file with the same contents, even when both and source and destination are on tmpfs. This is *exceptionally* true when verbose logging is enabled (implying that we're blocking on log flushes).

Both the below are best-of-three:

```
$ rm -rf test.tar.d && mkdir test.tar.d && time tar -xf test.tar -C test.tar.d
real	0m0.245s
user	0m0.039s
sys	0m0.204s
$ rm -rf test.catar.d && mkdir test.catar.d && catar extract test.catar{,.d}
real	0m0.798s
user	0m0.423s
sys	0m0.372s
```

Unfortunately, this scales up: An install process that took 15 minutes when using tar is well over 30 when using casync, *even from a reconstructed catar rather than a series of separate chunks*.

**Comment by keszybz** [comment]
Indeed. catars seem to be always uncompressed (an bug or missing feature?), and I get similar sizes for .catar and (uncompressed) .tar archives, and about 2× slower extraction to tmpfs with casync.

**Comment by charles-dyfis-net** [comment]
@keszybz, insofar as catar is a format that's expected to be chunked, "uncompressed" makes sense to me here -- you want to do compression *after* splitting into chunks to find as many similarities as possible.

**Comment by poettering** [comment]
Well, the comparison is not precisely fair, as casync tries to read/write more metadata from the file system that tar doesn't normally cover, and this results in a lot more system calls per file, as we need to query/reapply this metadata. In order to compare this more fairly, you'd have to use --with=/--without= to make casync save/restore the exact same metadata bits as your tar invocation would...

Also, we validate what we wrote after writing things, since we care about reproducibility, and the kernel silently eats up some of our adjustments otherwise in certain conditions. (for example, mtime granularity). We should add a "--best-effort" switch eventually, to turn off this verification, which also would speed things up a bit...

So, I am not saying we couldn't optimize things, but we do more stuff, hence we are slower...
