### ISSUE TITLE
Ubuntu ppa

### ISSUE THREAD

**Issue by zonque** [systemd/casync#15]
Can we get a ppa for casync as soon as the first release is made?
I'm looking at you, @martinpitt :)

**Comment by martinpitt** [comment]
Sure! I did some initial packaging. I pushed it to https://github.com/systemd/casync/tree/debian-packaging for the time being, but once this gets released I'll move that to anonscm.debian.org instead (so forgive me for being sloppy..)

I uploaded this to https://launchpad.net/~pitti/+archive/ubuntu/casync . Note that I had to make the tests non-fatal due to issue #20.

**Comment by martinpitt** [comment]
Nevermind, I moved the packaging to https://github.com/martinpitt/casync/tree/debian-packaging now as I need a fork for some other fixes anyway.

Build succeeded on amd64 but [fails on i386](https://launchpadlibrarian.net/323130663/buildlog_ubuntu-zesty-i386.casync_0.0+git20170608_BUILDING.txt.gz) due to a type declaration bug, I sent PR #21 for that.

**Comment by martinpitt** [comment]
I slurped in the type fix, and it built on i386 too now. I'll watch out for release announcements, or prod me if you want me to upload a new snapshot.

**Comment by poettering** [comment]
@martinpitt Thanks a ton for working on this!
