### ISSUE TITLE
Can we use casync tool in Linux Kernel 3.0 or less?

### ISSUE THREAD

**Issue by akhilpathania** [systemd/casync#182]
Can we use casync tool in Linux Kernel 3.0 or less?

**Comment by poettering** [comment]
we use a number of kernel features that are relatively new. However, for most we should have fallbacks. I figure you have to test this yourself, since I don#t have easy access to such an old kernel myself.

We'd merge patches fixing any incompat with such old kernels. Hence, If you play around with this and have some patches, please submit them upstream and we should be able to merge them here.

**Comment by poettering** [comment]
Anyway, I doubt we can answer this question here. Which means this issue isn't really actionable for us. Please try, and file issues or even better PRs for every incompat you find! thanks! Let's close this here for now.
