### ISSUE TITLE
Swappable compression tool

### ISSUE THREAD

**Issue by gyscos** [systemd/casync#24]
Hi.

Could `casync` take an option for a custom compression/decompression tool? `lzma` makes some speed tradeoffs that may not always be desirable (especially regarding decompression speed). Something similar to `tar`'s `-I, --use-compress-program=COMMAND` would be nice.

Though allowing clients to auto-detect the decompression tool to use may require a change in the index format (or maybe use magic numbers to identify the compression format) . :-/

I would understand if using a single compression format was a intentional decision, but this was not mentioned in the blog post or the Readme.

**Comment by julian-klode** [comment]
I agree. xz achieves a throughput of 5 MB/s or so, that's not really useful. With my borg backups, I use lz4 which achieves a relatively good compression at a very high speed. A good allrounder is zstd, it's a bit slower than lz4 and a bit less effective than xz, but it's a good overall match if you want to pick just one algorithm.

**Comment by julian-klode** [comment]
Reference points, for my Documents folder (which also contains a few git projects):

uncompressed: 1.8 GB
borg with lz4:    1.2 GB in 0m34s (1.3 GB without deduplication)
casync:             1.1 GB in 7m47s

**Comment by poettering** [comment]
This is now implemented with a898582529223d30f6d1067ddef9959ee57b588f and effa00a970a5bc8d0543d55d5e9fd5a2f5b0f9f3. The new code supports xz, gzip and zstd, the latter being the new default. We can support others as the need arises. This does not support invoking external programs for compression, for two reasons: performance (as we need to do this repeatedly for each chunk) and because we need some better understanding of the algorithms so that we can automatically detect which format is used for a chunk, to make things entirely automatic (i.e. regardless which one you picked when making archives, casync figures out the right algorithm to use for decompression automatically when you extract them again).

Closing.
