### ISSUE TITLE
Cleanup chunk store after removing archive

### ISSUE THREAD

**Issue by gyscos** [systemd/casync#43]
There is currently no easy way to remove unused chunks from a chunk store (an equivalent to `borg delete`).

Scenario: a single chunk store is re-used for multiples archives (periodic backups, independent images using de-duplication, ...).
At some point, some archives are no longer required. The `.cai?x` files are deleted, but the chunks are still present in the chunk store. Some chunks are used by other archives, some aren't. A way to remove chunks not present in existing archives would allow to save space. On continuously used stores (daily backups with a fixed number of images kept), this can avoid wasting significant space.

EDIT: My bad, I suppose this is the (not implemented yet) `casync gc` mentioned in the Readme.

**Comment by keszybz** [comment]
I'm working on this.

**Comment by poettering** [comment]
so i thought how to implement "casync gc" best, and the major complexity I saw was that we should make sure that "casync gc" can work remotely. To make that happen the protocol needs to be extended, but in a non-trivial way I figure, so that .caidx files stored locally, remotely and everywhere else can be considered to determine which chunks to keep. And I figure to do this in the best way we'd first have to compile the list of chunks that local caidx files need and then send that over to the server, and than on the server add in all chunks that caidx files on the same server need, if you follow what i mean...
